# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stanford CyberText
email: texttechnologies@lists.stanford.edu
description: >- # this means to ignore newlines until "baseurl:"
  The CyberText Technologies Project catalogues the history of dominant text-based human communication devices in an effort to identify common traits. We use those traits to discover the patterns that can predict the future of modern-day technologies. Which text technologies are going to succeed and how can they best be developed? The answer lies in the patterns of the past.
twitter_username: https://twitter.com/etreharne
repository: "username/repo-name"
minimal_mistakes_skin: dark
search: false
atom_feed:
  hide: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
paginate: 0 # amount of posts to show
paginate_path: /page:num/
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/etreharne"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      class: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
